// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SubtractRequest struct {
	A int `json:"a"`
	B int `json:"b"`
}

type SubtractResponse struct {
	Result int `json:"result"`
}

type SumRequest struct {
	A int `json:"a"`
	B int `json:"b"`
}

type SumResponse struct {
	Result int `json:"result"`
}
